### ISSUE TITLE
Error: Units are not configured in MELCloud service.

### ISSUE THREAD

**Issue by fjosef1** [grzegorz914/homebridge-melcloud-control#117] opened 2024-05-20 14:19 UTC
Any ideas what might be causing this error please  "Units are not configured in MELCloud service."
On MelCloud portal iI can see it's configured fine 

<img width="305" alt="image" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/124032412/efbc3263-2d18-40a9-abe2-a480d301e059">

```
[5/20/2024, 2:16:57 PM] [melcloudcontrol] Air Conditioner, Office , debug: Account Info: {
  "ContextKey": "removed",
  "Client": "removed",
  "Terms": 1284,
  "AL": 1,
  "ML": 0,
  "CMI": true,
  "IsStaff": false,
  "CUTF": false,
  "CAA": false,
  "ReceiveCountryNotifications": false,
  "ReceiveAllNotifications": false,
  "CACA": false,
  "CAGA": false,
  "MaximumDevices": 10,
  "ShowDiagnostics": false,
  "Language": 0,
  "Country": 237,
  "RealClient": 0,
  "Name": "removed",
  "UseFahrenheit": false,
  "Duration": 525600,
  "Expiry": "2025-05-20T14:16:45.76",
  "CMSC": false,
  "PartnerApplicationVersion": null,
  "EmailSettingsReminderShown": true,
  "EmailUnitErrors": 1,
  "EmailCommsErrors": 1,
  "ChartSeriesHidden": 0,
  "DeletePending": false,
  "Throttle": true,
  "IsImpersonated": false,
  "LanguageCode": "en",
  "CountryName": "United Kingdom",
  "CurrencySymbol": "£",
  "SupportEmailAddress": "melcloud.support@meuk.mee.com",
  "DateSeperator": "/",
  "TimeSeperator": ":",
  "AtwLogoFile": "ecodan_logo.png",
  "DECCReport": true,
  "CSVReport1min": true,
  "HidePresetPanel": false,
  "EmailSettingsReminderRequired": false,
  "TermsText": null,
  "MapView": false,
  "MapZoom": 5,
  "MapLongitude": "removed",
  "MapLatitude": "removed",
  "Throttled": false,
  "ClientId": "removed"
}
```

**Comment by fjosef1** [comment] 2024-05-20 14:56
Thank you @grzegorz914  
I thought this might be the reason why I'm not seeing the units in HomeKit but that's not it then.

I tried deleting the Bridge and adding it again.
Tried deleting the cache and restarting homebridge but still can't get the units to show in HomeKit.

Any suggestions I might of missed out?

**Comment by grzegorz914** [comment] 2024-05-20 15:00
Are you try this https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by grzegorz914** [comment] 2024-07-21 08:30
I close this as resolved because main issue is not a bug.

**Closed** 2024-07-21 08:31 UTC
